name = "AcceleratedKernels"
uuid = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"
authors = ["Andrei-Leonard Nicusan <leonard@evophase.co.uk> and contributors"]
version = "0.2.3"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[weakdeps]
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[extensions]
AcceleratedKernelsMetalExt = "Metal"
AcceleratedKernelsoneAPIExt = "oneAPI"

[compat]
ArgCheck = "2"
DocStringExtensions = "0.9"
GPUArraysCore = "0.1, 0.2"
KernelAbstractions = "0.9"
Markdown = "1"
Metal = "1"
OhMyThreads = "0.7"
Polyester = "0.7"
Unrolled = "0.1"
julia = "1.10"
oneAPI = "1, 2"
