name = "AcceleratedKernels"
uuid = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"
authors = ["Andrei-Leonard Nicusan <leonard@evophase.co.uk> and contributors"]
version = "0.1.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"

[compat]
julia = "1.6.7"
DocStringExtensions = "0.9"
GPUArrays = "10"
KernelAbstractions = "0.9"
Polyester = "0.7"

