steps:
  - label: "AMDGPU - Julia v1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
    command: |
      julia -e 'using Pkg

                println("--- :julia: Instantiating environment")
                Pkg.add("AMDGPU")
                Pkg.develop(path=".")

                println("+++ :julia: Running tests")
                Pkg.test("AcceleratedKernels", test_args=["--AMDGPU"])'
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

  - label: "AMDGPU - Julia v1.11"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
    command: |
      julia -e 'using Pkg

                println("--- :julia: Instantiating environment")
                Pkg.add("AMDGPU")
                Pkg.develop(path=".")

                println("+++ :julia: Running tests")
                Pkg.test("AcceleratedKernels", test_args=["--AMDGPU"])'
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60
