steps:

  # CUDA
  - label: "CUDA - Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
          - "1.11"
          - "1.12"
          - "1.13"
          - "nightly"
      adjustments:
        - with:
            version: "nightly"
          soft_fail: true
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
    command: |
      julia -e 'using Pkg
                println("--- :julia: Instantiating environment")
                Pkg.develop(path=".")
                println("+++ :julia: Running tests")
                Pkg.test("AcceleratedKernels", test_args=["--cuda"])'
    agents:
      queue: "cuda"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

  # AMDGPU
  - label: "AMDGPU - Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
          - "1.11"
          - "1.12"
          - "1.13"
          - "nightly"
      adjustments:
        - with:
            version: "nightly"
          soft_fail: true
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
    command: |
      julia -e 'using Pkg
                println("--- :julia: Instantiating environment")
                Pkg.develop(path=".")
                println("+++ :julia: Running tests")
                Pkg.test("AcceleratedKernels", test_args=["--amdgpu"])'
    agents:
      queue: "rocm"
      rocmgpu: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

  # oneAPI
  - label: "oneAPI - Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
          - "1.11"
          - "1.12"
          - "1.13"
          - "nightly"
      adjustments:
        - with:
            version: "nightly"
          soft_fail: true
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
    command: |
      julia -e 'using Pkg
                println("--- :julia: Instantiating environment")
                Pkg.develop(path=".")
                println("+++ :julia: Running tests")
                Pkg.add(url="https://github.com/christiangnrd/oneAPI.jl", rev="usefree")
                Pkg.test("AcceleratedKernels", test_args=["--oneapi"])'
    agents:
      queue: "oneapi"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

  # Metal
  - label: "Metal - Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
          - "1.11"
          - "1.12"
          - "1.13"
          - "nightly"
      adjustments:
        - with:
            version: "nightly"
          soft_fail: true
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
    command: |
      julia -e 'using Pkg
                println("--- :julia: Instantiating environment")
                Pkg.develop(path=".")
                println("+++ :julia: Running tests")
                Pkg.test("AcceleratedKernels", test_args=["--metal"])'
    agents:
      queue: "metal"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

env:
  JULIA_PKG_PRECOMPILE_AUTO: false
